name: Oxfmt

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/setup@v2.1.0
        with:
          runtime: node@26
          cache: true
          require-lockfile: true

      - run: pnpm run check:format
